name: debug_sheet_example
description: Example app for debug_sheet package.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  debug_sheet:
    path: ../
  get_storage: ^2.1.1
